server:
  port: 6868
eureka:
  client:
    register-with-eureka: false #服务器本身不注册
    fetch-registry: false  #是否从eureka中获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
spring:
  rabbitmq:
    host: 192.168.114.133
