server:
  port: 8010
spring:
  application:
    name: tensquare_search
  data:
    elasticsearch:
      cluster-nodes: 192.168.114.133:9300
#      repositories:
#        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #跨域