server:
  port: 8012
spring:
  application:
    name: tensquare‐sms #指定服务名
  rabbitmq:
    host: 192.168.114.133
#aliyun:
#  sms:
#    accessKeyId:
#    accessKeySecret:
#    template_code:
#    sign_name:
